
/*LOCK TABLES `STATUS` WRITE*/;
/*LOCK TABLES `STATUS` WRITE, `STATUS` AS t1 READ*/;
/*!40000 ALTER TABLE `STATUS` DISABLE KEYS */;
INSERT INTO `STATUS`(ID, STATUS_TYPE)
SELECT * FROM (SELECT 1,'SUCCESS') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `STATUS` WHERE ID = 1
) LIMIT 1;
INSERT INTO `STATUS`(ID, STATUS_TYPE)
SELECT * FROM (SELECT 2,'FAILURE') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `STATUS` WHERE ID = 2
) LIMIT 1;
/*!40000 ALTER TABLE `STATUS` ENABLE KEYS */;
/*UNLOCK TABLES*/;


/*LOCK TABLES `PIPELINE` WRITE*/;
/*LOCK TABLES `PIPELINE` WRITE, `PIPELINE` AS t1 READ*/;
/*!40000 ALTER TABLE `PIPELINE` DISABLE KEYS */;

INSERT INTO `PIPELINE`(ID,PIPELINE_TYPE)
SELECT * FROM (SELECT 1,'CosmostoDb2Sync - Summary') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `PIPELINE` WHERE ID = 1
) LIMIT 1;

INSERT INTO `PIPELINE`(ID,PIPELINE_TYPE)
SELECT * FROM (SELECT 2,'CosmostoDb2Sync - SummaryLine') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `PIPELINE` WHERE ID = 2
) LIMIT 1;


INSERT INTO `PIPELINE`(ID,PIPELINE_TYPE)
SELECT * FROM (SELECT 3,'Db2toCosmosStore- Summary') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `PIPELINE` WHERE ID = 3
) LIMIT 1;


INSERT INTO `PIPELINE`(ID,PIPELINE_TYPE)
SELECT * FROM (SELECT 4,'Db2toCosmosStore - Line') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `PIPELINE` WHERE ID = 4
) LIMIT 1;


INSERT INTO `PIPELINE`(ID,PIPELINE_TYPE)
SELECT * FROM (SELECT 5,'Db2toCosmosWarehouse - Summary') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `PIPELINE` WHERE ID = 5
) LIMIT 1;


INSERT INTO `PIPELINE`(ID,PIPELINE_TYPE)
SELECT * FROM (SELECT 6,'Db2toCosmosWarehouse - Line') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `PIPELINE` WHERE ID = 6
) LIMIT 1;

INSERT INTO `PIPELINE`(ID,PIPELINE_TYPE)
SELECT * FROM (SELECT 7,'Db2toCosmosStore - Exclusion') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `PIPELINE` WHERE ID = 7
) LIMIT 1;

INSERT INTO `PIPELINE`(ID,PIPELINE_TYPE)
SELECT * FROM (SELECT 8,'Db2toCosmosWareHouse - Exclusion') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `PIPELINE` WHERE ID = 8
) LIMIT 1;

/*!40000 ALTER TABLE `PIPELINE` ENABLE KEYS */;
/*UNLOCK TABLES*/;


/*LOCK TABLES `APPLICATION` WRITE*/;
/*LOCK TABLES `APPLICATION` WRITE, `APPLICATION` AS t1 READ*/;
/*!40000 ALTER TABLE `APPLICATION` DISABLE KEYS */;
INSERT INTO `APPLICATION`(ID,APP_NAME)
SELECT * FROM (SELECT 1,'JDBC-Connector') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `APPLICATION` WHERE ID = 1
) LIMIT 1;

INSERT INTO `APPLICATION`(ID,APP_NAME)
SELECT * FROM (SELECT 2,'Sink') AS tmp
WHERE NOT EXISTS (
    SELECT ID FROM `APPLICATION` WHERE ID = 2
) LIMIT 1;
/*!40000 ALTER TABLE `APPLICATION` ENABLE KEYS */;
/*UNLOCK TABLES*/;
