SET NAMES utf8 ;


 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE IF NOT EXISTS `STATUS` (
   `ID` int(11) NOT NULL,
   `STATUS_TYPE` varchar(45) COLLATE utf8mb4_general_ci NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
   PRIMARY KEY (`ID`),
   UNIQUE KEY `ID_UNIQUE` (`ID`),
   UNIQUE KEY `STATUS_TYPE_UNIQUE` (`STATUS_TYPE`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE IF NOT EXISTS `PIPELINE` (
   `ID` int(11) NOT NULL,
   `PIPELINE_TYPE` varchar(45) COLLATE utf8mb4_general_ci NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
   PRIMARY KEY (`ID`),
   UNIQUE KEY `ID_UNIQUE` (`ID`),
   UNIQUE KEY `PIPELINE_TYPE_UNIQUE` (`PIPELINE_TYPE`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE IF NOT EXISTS `APPLICATION` (
   `ID` int(11) NOT NULL,
   `APP_NAME` varchar(45) COLLATE utf8mb4_general_ci NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
   PRIMARY KEY (`ID`),
   UNIQUE KEY `ID_UNIQUE` (`ID`),
   UNIQUE KEY `APP_NAME_UNIQUE` (`APP_NAME`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



  SET character_set_client = utf8mb4 ;
  CREATE TABLE IF NOT EXISTS `RECEIVINGS_SUCCESS` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `STATUS_ID` int(11) NOT NULL,
    `PIPELINE_ID` int(11) NOT NULL,
    `COSMOS_ID` varchar(1000) COLLATE utf8mb4_general_ci NOT NULL,
    `PAYLOAD` varchar(15000) COLLATE utf8mb4_general_ci DEFAULT NULL,
     CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
     UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    `DB2_TIMESTAMP` varchar(45) COLLATE utf8mb4_general_ci DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `FK_STATUS_idx` (`STATUS_ID`),
    KEY `FK_PIPELINE_idx` (`PIPELINE_ID`),
    CONSTRAINT `FK_PIPELINE` FOREIGN KEY (`PIPELINE_ID`) REFERENCES `pipeline` (`ID`),
    CONSTRAINT `FK_STATUS` FOREIGN KEY (`STATUS_ID`) REFERENCES `status` (`ID`)
  ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


  SET character_set_client = utf8mb4 ;
  CREATE TABLE IF NOT EXISTS `RECEIVINGS_FAILURE` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `STATUS_ID` int(11) NOT NULL,
    `PIPELINE_ID` int(11) NOT NULL,
    `APP_ID` int(11) NOT NULL,
    `COSMOS_ID` varchar(1000) COLLATE utf8mb4_general_ci NOT NULL,
    `ERROR_CODE` varchar(45) COLLATE utf8mb4_general_ci DEFAULT NULL,
    `ERROR_MESSAGE` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
    `DETAILS` varchar(4000) COLLATE utf8mb4_general_ci DEFAULT NULL,
    `PAYLOAD` varchar(10000) COLLATE utf8mb4_general_ci DEFAULT NULL,
     CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
     UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    `DB2_TIMESTAMP` varchar(45) COLLATE utf8mb4_general_ci DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `FK_STATUS_idx` (`STATUS_ID`),
    KEY `FK_PIPELINE_idx` (`PIPELINE_ID`),
    KEY `FK_APPLICATION_idx` (`APP_ID`),
    CONSTRAINT `FK_APPLICATION_ERROR` FOREIGN KEY (`APP_ID`) REFERENCES `application` (`ID`),
    CONSTRAINT `FK_PIPELINE_ERROR` FOREIGN KEY (`PIPELINE_ID`) REFERENCES `pipeline` (`ID`),
    CONSTRAINT `FK_STATUS_ERROR` FOREIGN KEY (`STATUS_ID`) REFERENCES `status` (`ID`)
  ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



  SET character_set_client = utf8mb4 ;
 CREATE TABLE IF NOT EXISTS `METRICS` (
   `ID` int(11) NOT NULL AUTO_INCREMENT,
   `PIPELINE_ID` int(11) DEFAULT NULL,
   `REPORT_DATE` date DEFAULT NULL,
   `RECORD_COUNT` bigint(40) NOT NULL,
   `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`ID`),
   KEY `FK_PIPELINE_idx` (`PIPELINE_ID`),
   CONSTRAINT `FK_PIPELINE_METRIC` FOREIGN KEY (`PIPELINE_ID`) REFERENCES `pipeline` (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

